### ISSUE TITLE
unexpected behavior changes since 0.99

### ISSUE THREAD

**Issue by toddr** [toddr/CDB_File#12]
From: Marc Lehmann

Sorry to write so many mails, but it seems CDB_File is utterly broken in current versions.

For example, in this code:

```perl
  $CDB = CDB_File->TIEHASH ($rijkfs::CDB_FILE)
     or die "$rijkfs::CDB_FILE: tie failed…\n";

  for (my $k = $CDB->FIRSTKEY; defined $k; $k = $CDB->NEXTKEY ($k)) {
     #last if $k eq pack "H*", "53bad4b11d";
  }

  ddx $CDB->FETCH (pack "H*", "53bad4b11d");
```

FETCH returns "undef"_unless_ I uncomment the "last if.." in the loop. That is, FETCH only works properly for keys currently iterated over. This is not universally true, FETCH sometimes works for some keys, but it's simply not reliable.

Turns out a lot of my problems is because somebody upgraded CDB_File in our perl from 0.99 (which is still not able to create cdbs in reasonable time) to 1.02, which is completely broken at the moment.

**Comment by stdweird** [comment]
@toddr as 1.02 hit EPEL repos, we are in similar situation. is there any progress on this issue?
also, do you know which commit or PR makes up the 1.02 release?

**Comment by toddr** [comment]
looking into it now.

**Comment by toddr** [comment]
@stdweird I'm actually looking to make a test case and struggling to reproduce it.
