### ISSUE TITLE
Warning when storing undef as a value.

### ISSUE THREAD

**Issue by aleksey-mashanov** [toddr/CDB_File#15]
```
$ perl -MCDB_File -we 'tie my %h, "CDB_File", "empty.cdb" or die; my %x = %h; my $y = $h{key};'
Use of uninitialized value in subroutine entry at -e line 1.
```
it is from `CDB_File.xs:463`:
```
    if (this->end && sv_eq(this->curkey, k)) {
```
`this->curkey` is undefined.
Warning exists only if CDB file is empty.

**Comment by toddr** [comment]
Yep. Makes sense. I'm looking into it now.

**Comment by toddr** [comment]
BTW it's not currently possible to store undef as a value in CDB_File.

**Comment by toddr** [comment]
the CDB_File format does not have any concept of a NULL or undef. I could in theory just NOT store keys with an undef value but then EXISTS would return incorrectly.

**Comment by toddr** [comment]
The warning in question shouldn't happen any more since we no longer store curkey as an sv.

**Comment by toddr** [comment]
Actually now I'm explicitly warning about undef keys or values as of e580e9e64e2f424053bb38a1580d80a67baa401d

**Comment by aleksey-mashanov** [comment]
The issue is not about `undef` in keys or values, it's about CDB files without key/value pairs at all.
A little bit more explicit example:
```sh
~$ perl -MCDB_File -we 'my $cdb = CDB_File->new("empty.cdb", "empty.cdb.tmp") or die; $cdb->finish()'
~$ perl -MCDB_File -we 'tie my %h, "CDB_File", "empty.cdb" or die; my %x = %h; my $y = $h{key};'
Use of uninitialized value in subroutine entry at -e line 1.
```

Anyway, the code in master is not affected by this issue now. Thanks!

**Comment by toddr** [comment]
I don't see that happening in 1.04. Do you?

**Comment by toddr** [comment]
I have added these tests to confirm it behaves correctly. 495d9eb7a40b18df29fe3c52e8cb9dbedbdf61a6
